name: Docker Build and Push to ACR
 
on:
  push:
    branches: [ "build-image" ]  # 或者你想要触发构建的分支
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
 
    - name: Login to ACR
      uses: docker/login-action@v1 
      with:
        registry: crpi-95ycgp634fv97mlw.cn-hangzhou.personal.cr.aliyuncs.com
        username: ${{ secrets.ACR_USERNAME }}  # 这里填写你的 AccessKey id
        password: ${{ secrets.ACR_PASSWORD }}  # 这里填写你的 AccessKey Secret
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Dockerfile 所在的目录路径
        push: true  # 设置为 true 以推送镜像到仓库
        tags: crpi-95ycgp634fv97mlw.cn-hangzhou.personal.cr.aliyuncs.com/pengfei-y/dm:mvn  # 替换为你的命名空间和仓库名以及标签
